apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: churn-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourname/churn-mlops.git
    targetRevision: main
    path: helm/churn-api
  destination:
    server: https://kubernetes.default.svc
    namespace: churn-dev