apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "churn-api.labels" . | nindent 4 }}
  name: churn-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: churn-api
  template:
    metadata:
      labels:
        app: churn-api
    spec:
      containers:
        - name: churn-api
          image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DECISION_THRESHOLD
              value: {{ .Values.decisionThreshold | quote }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}